services:
  nginx-load-balancer:
    image: nginx:1.14
    container_name: nginx-load-balancer
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: host