services:
  nginx:
    image: nginx:1.14
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
