---
- name: Setup Docker Engine and Docker Compose
  hosts: csc_vm
  become: true  # Run tasks with sudo
  tasks:
    - name: Create directory for Docker Compose plugins
      file:
        path: ~/.docker/cli-plugins/
        state: directory
        mode: '0755'

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64
        dest: ~/.docker/cli-plugins/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      shell: docker compose version
      register: docker_compose_version

    - name: Display Docker Compose version
      debug:
        msg: "Docker Compose installed successfully: {{ docker_compose_version.stdout }}"
