---
- name: Configure Docker with Persistent Volume
  hosts: csc_vm
  become: true
  tasks:

    # Task 1: Install Docker Engine
    - name: Install Docker Engine
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

    # Task 2: Add User to Docker Group
    - name: Add user to Docker group
      shell: |
        groupadd -f docker
        usermod -aG docker $USER
      args:
        warn: false

    # Task 3: Install Docker Compose
    - name: Install Docker Compose
      shell: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 \
          -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose
      args:
        creates: ~/.docker/cli-plugins/docker-compose

    # Task 4: Stop Docker Service
    - name: Stop Docker service
      service:
        name: docker
        state: stopped

    # Task 5: Backup Existing Docker Daemon Configuration
    - name: Backup existing Docker daemon configuration
      copy:
        src: /etc/docker/daemon.json
        dest: /etc/docker/daemon.json.bak
        remote_src: true
      ignore_errors: true  # Avoid failing the playbook if the file doesn't exist

    # Task 6: Create New Docker Directory on Persistent Volume
    - name: Create new Docker directory on persistent volume
      file:
        path: /media/volume/docker
        state: directory
        owner: root
        group: root
        mode: '0755'

    # Task 7: Move Existing Docker Data to Persistent Volume
    - name: Move existing Docker data to the new location
      shell: |
        if [ -d /var/lib/docker ]; then
          mv /var/lib/docker/* /media/volume/docker/
        fi
      args:
        creates: /media/volume/docker/

    # Task 8: Update Docker Daemon Configuration
    - name: Update Docker daemon configuration
      blockinfile:
        path: /etc/docker/daemon.json
        create: yes
        block: |
          {
            "data-root": "/media/volume/docker"
          }

    # Task 9: Restart Docker Service
    - name: Restart Docker service
      service:
        name: docker
        state: started
