---
- name: Configure Docker with Persistent Volume
  hosts: csc_vm
  become: true
  tasks:
    - name: Ensure the persistent volume is formatted as ext4
      filesystem:
        fstype: ext4
        dev: /dev/vdb

    - name: Create the mount point directory
      file:
        path: /media/volume/docker
        state: directory
        mode: '0755'

    - name: Mount the persistent volume to the directory
      mount:
        path: /media/volume/docker
        src: /dev/vdb
        fstype: ext4
        state: mounted

    - name: Persist the mount in fstab
      lineinfile:
        path: /etc/fstab
        line: "/dev/vdb /media/volume/docker ext4 defaults 0 0"
        state: present

    # Task 4: Stop Docker Service
    - name: Stop Docker service
      service:
        name: docker
        state: stopped

    # Task 5: Backup Existing Docker Daemon Configuration
    - name: Backup existing Docker daemon configuration
      copy:
        src: /etc/docker/daemon.json
        dest: /etc/docker/daemon.json.bak
        remote_src: true
      ignore_errors: true  # Avoid failing the playbook if the file doesn't exist

    # Task 6: Create New Docker Directory on Persistent Volume
    - name: Create new Docker directory on persistent volume
      file:
        path: /media/volume/docker
        state: directory
        owner: root
        group: root
        mode: '0755'

    # Task 7: Move Existing Docker Data to Persistent Volume
    - name: Move existing Docker data to the new location
      shell: |
        if [ -d /var/lib/docker ]; then
          mv /var/lib/docker/* /media/volume/docker/
        fi
      args:
        creates: /media/volume/docker/

    # Task 8: Update Docker Daemon Configuration
    - name: Update Docker daemon configuration
      blockinfile:
        path: /etc/docker/daemon.json
        create: yes
        block: |
          {
            "data-root": "/media/volume/docker"
          }

    # Task 9: Restart Docker Service
    - name: Restart Docker service
      service:
        name: docker
        state: started
