---
# Based on https://tienbm90.medium.com/how-to-change-docker-root-data-directory-89a39be1a70b/
- name: Configure Docker with Persistent Volume
  hosts: csc_vm
  become: true
  tasks:

    # 1. Stop the docker daemon
    - name: Stop Docker service
      service:
        name: docker
        state: stopped

    # 2. Add a configuration file to tell the docker daemon what is the location of the data directory
    - name: Copy daemon.json if it does not exist
      copy:
        src: ../config/docker/daemon.json
        dest: /etc/docker/daemon.json
        force: no
      ignore_errors: no

    # 3. Copy the current data directory to the new one
    - name: Synchronize and copy Docker data to new root
      shell: |
        rsync -aP /var/lib/docker "/media/volume/docker"
        cp -rp /var/lib/docker/* "/media/volume/docker"
      ignore_errors: no

    # 4. Rename the old docker directory
    - name: Move old Docker data directory
      command: mv /var/lib/docker /var/lib/docker.old

    # 5. Restart the docker daemon
    - name: Start Docker service
      service:
        name: docker
        state: started