services:
  portainer:
    image: portainer/portainer-ce:2.21.4
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"  # Agent communication port
      - "9443:9443"  # HTTPS GUI port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Access to the Docker socket
      - portainer_data:/data                       # Persistent data storage

volumes:
  portainer_data: